### ISSUE TITLE
Repo is incomplete

### ISSUE THREAD

**Issue by tindsorm** [FreeApophis/fcp2lib.NET#1]
The project files reference files/directories that don't exist in the repo:
FCP2lib\Protocol\MessageEventFactory.cs
FCP2example

Can these be committed?

**Comment by FreeApophis** [comment]
I'll take a look what the issue is...

**Comment by FreeApophis** [comment]
Just removed all the references. 
They are not necessary.

**Comment by tindsorm** [comment]
The example project would've been helpful, but I've figured some of it out anyway.

**Comment by FreeApophis** [comment]
Yes, I understand that. Feel free to ask questions. 

The Interface should be well documented. Use the FCP2Protocol class for everything. The Client, Upload and Download classes were never implemented, the idea was to have a simpler interface without to know the exact workings of FCP2.

**Comment by FreeApophis** [comment]
Very Basic Test added, can also be used as a minimal example.

**Comment by tindsorm** [comment]
Thanks, that helped.
Though the test, as well as my own code are throwing exceptions on Disconnect()
```
------ Run test started ------
System.IO.IOException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall. ---> System.Net.Sockets.SocketException: A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at FCP2.Protocol.MixedReader.ReadLine() in C:\Users\Admin\Documents\Visual Studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\MixedReader.cs:line 55
   at FCP2.Protocol.FCP2Protocol.MessageParser() in C:\Users\Admin\Documents\Visual Studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\FCP2Protocol.cs:line 300
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at FCP2.Protocol.MixedReader.ReadLine() in C:\Users\Admin\Documents\Visual Studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\MixedReader.cs:line 55
   at FCP2.Protocol.FCP2Protocol.MessageParser() in C:\Users\Admin\Documents\Visual Studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\FCP2Protocol.cs:line 300
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.IO.IOException: Unable to read data from the transport connection: A blocking operation was interrupted by a call to WSACancelBlockingCall. ---> System.Net.Sockets.SocketException: A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at FCP2.Protocol.MixedReader.ReadLine() in C:\Users\Admin\Documents\Visual Studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\MixedReader.cs:line 55
   at FCP2.Protocol.FCP2Protocol.MessageParser() in C:\Users\Admin\Documents\Visual Studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\FCP2Protocol.cs:line 300
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at FCP2.Protocol.MixedReader.ReadLine() in C:\Users\Admin\Documents\Visual Studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\MixedReader.cs:line 55
   at FCP2.Protocol.FCP2Protocol.MessageParser() in C:\Users\Admin\Documents\Visual Studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\FCP2Protocol.cs:line 300
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
========== Run test finished: 2 run (0:00:02.3261969) ==========
```

**Comment by FreeApophis** [comment]
I can reproduce it, the Parser Thread is still reading on the dead Stream.

**Comment by FreeApophis** [comment]
Fixed the Exception, I catch the exception and Join the Parser Thread on Disconnect.

Since the Read is blocking, the only simple alternative would be to Abort the Thread and that Exception is not nice to handle either. To really fix this, the Reader would need to have a time out.
