### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by tindsorm** [FreeApophis/fcp2lib.NET#3]
After fixing the exception I submitted a PR for, I now get this one:
```
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
       at FCP2.Protocol.DynamicReturnValue.Init() in C:\Users\Admin\Documents\visual studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\DynamicReturnValue.cs:line 43
       at FCP2.Protocol.DynamicReturnValue.TryConvert(ConvertBinder binder, Object& result) in C:\Users\Admin\Documents\visual studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\DynamicReturnValue.cs:line 73
       at CallSite.Target(Closure , CallSite , Object )
       at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       at FCP2.EventArgs.NodeHelloEventArgs..ctor(Object parsed) in C:\Users\Admin\Documents\visual studio 2015\Projects\fcp2lib.NET\FCP2lib\EventArgs\NodeHelloEventArgs.cs:line 51
       at FCP2.Protocol.FCP2Protocol.CreateEvent(String line) in C:\Users\Admin\Documents\visual studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\FCP2Protocol.cs:line 295
       at FCP2.Protocol.FCP2Protocol.MessageParser() in C:\Users\Admin\Documents\visual studio 2015\Projects\fcp2lib.NET\FCP2lib\Protocol\FCP2Protocol.cs:line 286
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:
```

Not sure how to fix this. I've never seen `Contract.Requires` before. 
Would  `if (TypeTable.Count != 0) return` be the correct fix for this?

**Comment by FreeApophis** [comment]
I will install Freenet to check it out.

**Comment by FreeApophis** [comment]
The Pre-Condition of the Method is violated. The Init should only be called once. I am investigating why it isn't.

**Comment by FreeApophis** [comment]
Solved via Static Constructor. Cleaner than the Init Code so far, the Contract was correct, but there was a return in the previous code. Now it should work even with more than one Thread.
